package io.github.cactric.swalsh.ui.album;

import android.content.Intent;
import android.content.res.Resources;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;
import android.widget.ImageButton;
import android.widget.LinearLayout;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AlertDialog;
import androidx.recyclerview.widget.RecyclerView;

import java.util.ArrayList;

import io.github.cactric.swalsh.R;
import io.github.cactric.swalsh.databinding.DialogEditGameNameBinding;
import io.github.cactric.swalsh.databinding.RecyclerGamesBinding;
import io.github.cactric.swalsh.games.GameDatabase;
import io.github.cactric.swalsh.games.GameItem;
import io.github.cactric.swalsh.games.GameUtils;

public class GamePickerAdapter extends RecyclerView.Adapter<GamePickerAdapter.ViewHolder> {
    private final ArrayList<GameItem> gameItems;
    private final Resources res;

    public GamePickerAdapter(ArrayList<GameItem> gameItems, Resources res) {
        this.gameItems = gameItems;
        this.res = res;
    }

    @NonNull
    @Override
    public ViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        RecyclerGamesBinding binding = RecyclerGamesBinding.inflate(
                LayoutInflater.from(parent.getContext()),
                parent,
                false
        );
        return new ViewHolder(binding);
    }

    @Override
    public void onBindViewHolder(@NonNull ViewHolder holder, int position) {
        GameItem gameItem = gameItems.get(position);
        holder.getGameName().setText(gameItem.game().gameName);
        holder.getGameTotals().setText(res.getString(R.string.game_picker_total_format, gameItem.totalPics(), gameItem.totalVids()));

        holder.getGameRoot().setOnClickListener(v -> {
            Intent intent = new Intent(v.getContext(), AlbumActivity.class);
            intent.putExtra("EXTRA_GAME_ID", gameItem.game().gameId);
            v.getContext().startActivity(intent);
        });

        holder.getEditGameName().setOnClickListener(v -> {
            // Show a popup asking the user for the name
            AlertDialog.Builder builder = new AlertDialog.Builder(v.getContext());
            // First make the view for the EditText view in the dialog
            DialogEditGameNameBinding editBinding = DialogEditGameNameBinding.inflate(
                    LayoutInflater.from(v.getContext()),
                    null,
                    false
            );

            // Set the text to the old game name, if present
            // Presence is detected by whether the primary key has been changed from 0
            // (it is autogenerated on insertion into the database)
            if (gameItem.game().game_primary_key != 0) {
                editBinding.gameNameEntry.setText(gameItem.game().gameName);

                // Also add a Remove button if it's actually in the DB
                builder.setNeutralButton(R.string.clear_name, (dialog, which) -> {
                    new Thread(() -> {
                        GameDatabase db = GameDatabase.getDatabase(v.getContext());
                        db.gameDao().delete(gameItem.game());
                        GameUtils gameUtils = new GameUtils(v.getContext());
                        gameItems.set(position, gameUtils.lookupGameItem(gameItem.game().gameId));
                    }).start();
                    GamePickerAdapter.this.notifyItemChanged(position);
                });
            }
            builder.setView(editBinding.getRoot());
            builder.setTitle(R.string.edit_game_name_dialog_title);
            builder.setPositiveButton(R.string.save, (dialog, which) -> {
                // Save the name
                String name = editBinding.gameNameEntry.getText().toString();

                new Thread(() -> {
                    GameDatabase db = GameDatabase.getDatabase(v.getContext());
                    // Modify the gameName in the game object, then add it to the db to update it
                    gameItem.game().gameName = name;
                    db.gameDao().addGame(gameItem.game());
                    GameUtils gameUtils = new GameUtils(v.getContext());
                    // Fetch the game from the DB, mainly to get the primary key set
                    gameItems.set(position, gameUtils.getTotals(db.gameDao().findByGameId(gameItem.game().gameId)));
                }).start();
                GamePickerAdapter.this.notifyItemChanged(position);
            });
            builder.setNegativeButton(android.R.string.cancel, (dialog, which) -> dialog.dismiss());
            builder.show();
        });
    }

    @Override
    public int getItemCount() {
        return gameItems.size();
    }

    public static class ViewHolder extends RecyclerView.ViewHolder {
        private final RecyclerGamesBinding binding;

        public ViewHolder(RecyclerGamesBinding binding) {
            super(binding.getRoot());
            this.binding = binding;
        }

        public LinearLayout getGameRoot() {
            return binding.getRoot();
        }

        public TextView getGameName() {
            return binding.gameRecyclerName;
        }

        public ImageButton getEditGameName() {
            return binding.gameRecyclerEditName;
        }

        public TextView getGameTotals() {
            return binding.gameRecyclerAmount;
        }
    }
}
